# Generated by Django 3.2.5 on 2021-10-12 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211012_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.ForeignKey(default=1, help_text='Klik untuk memilih satu kategori.', on_delete=django.db.models.deletion.CASCADE, to='product.category'),
            preserve_default=False,
        ),
    ]
